### PR TITLE
Enable/disable autocomplete

### PR DESCRIPTION
**Pull request by chaudum**
It is now possible to disable autocompletion using ``--no-autocomplete`` command line argument and to toggle autocomplete using the ``\autocomplete`` crash command.

### CODE REVIEW

**Comment by mfussenegger** [comment]
I think we should consider adding a generic command for options that change the behaviour of crash e.g `\cset autocomplete on` or `\cset format dynamic`

But ack anyway

**Comment by chaudum** [comment]
I think that is a good idea @mfussenegger , especially in combination with a configuration file.
Guess that is something for a fun Friday evening with a pint ... 🤔

**Comment by ChrisChinchilla** [comment]
Some small fixes @chaudum

**Comment by celaus** [comment]
ACK

**Pull request merged**
