### PR TITLE
WIP: implement heartbeat to keep connection alive

### PR DESCRIPTION
**Pull request by chaudum**
## Summary of the changes / Why this is an improvement

@autophagy @mfussenegger Is the keep-alive feature of crash still a thing? It has been lying around on my local checkout for some time now and I am wondering whether I should get it over the finish line.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mfussenegger** [comment]
I'm not sure. `psql` suffers from the same problem when using it to connect to a cloud cluster. So I wonder if we can come up a solution that doesn't involve patching all clients.

**Comment by chaudum** [comment]
> I'm not sure. `psql` suffers from the same problem when using it to connect to a cloud cluster. So I wonder if we can come up a solution that doesn't involve patching all clients.

The very specific problem, however, occurs when using Azure Loadbalancer, which has an idle timeout of 4-30 minutes, but it is not possible to deactivate connection reset.
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout#tcp-idle-timeout
load-balancer/load-balancer-tcp-reset

**Comment by mfussenegger** [comment]
Instead of doing query-heartbeats we could also enable TCP-keep-alive.

[urllib3 docs has an example how to set that](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.connection.HTTPConnection)

**Comment by chaudum** [comment]
> Instead of doing query-heartbeats we could also enable TCP-keep-alive.
> 
> [urllib3 docs has an example how to set that](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.connection.HTTPConnection)

I will open an PR on crate-python.

**Pull request closed without merging**
